name = "JuliaScript"
uuid = "eac5aaee-ac7f-40cd-ab88-b72e0a6c4bd0"
authors = ["Stephan Sahm <stephan.sahm@jolin.io> and contributors"]
version = "0.1.0"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
PackageCompiler = "2.1"
SHA = "0.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
